[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[build.environment]
  NODE_VERSION = "22"
  VITE_IDENTITY_URL = "https://api.watadiq.com"
  VITE_WATAD_OAUTH_CLIENT_ID = "wat_lAe6tz8LRI3-c3509EYENRG-AHx803b-"
